export const longCourse = [
  {
    item: "VECTOR(10)",
    numb1: "1",
    time1: "2:08",
    intro1: "Vector Network",
    width1: "60",
    desc1: "Create interesting shapes using a web of vector points",
    numb2: "2",
    time2: "2:04",
    intro2: "Booleans",
    width2: "30",
    desc2: "Learn to apply Union, Subtract, Intersect and Exclude",
    numb3: "3",
    time3: "2:12",
    intro3: "Polygons",
    width3: "15",
    desc3: "Learn to apply Union, Subtract, Intersect and Exclude",
  },
  {
    item: "ADAPTIVE LAYOUT(2)",
    numb1: "1",
    time1: "2:08",
    intro1: "Auto Layout",
    width1: "65",
    desc1: "Create stacks of dynamic and highly editable elements",
    numb2: "2",
    time2: "2:12",
    intro2: "Constraints",
    width2: "70",
    desc2: "Create contrainsts to make your layout more adaptive",
    numb3: "3",
    time3: "2:12",
    intro3: "Components",
    width3: "40",
    desc3: "Create reusable elements across your entire app",
  },
];
export const longCourse2 = [
  {
    item: "Layout (10)",
    numb1: "1",
    time1: "4:08",
    intro1: "Smooth Corners",
    width1: "20",
    desc1: "Create Apple’s super ellipsis for your rectangles and stacks",
    numb2: "2",
    time2: "8:04",
    intro2: "Screen Dimensions",
    width2: "50",
    desc2: "Detect the screen width and height with GeometryReader’s values",
    numb3: "3",
    time3: "8:12",
    intro3: "Scroll Position",
    width3: "35",
    desc3:
      "Get the scroll position using GeometryReader’s minX and minY values",
  },
  {
    item: "Animation (9)",
    numb1: "1",
    time1: "10:00",
    intro1: "Lottie Animations",
    width1: "10",
    desc1: "Add Lottie animated assets to your project",
    numb2: "2",
    time2: "9:15",
    intro2: "Timing Curve Animation   ",
    width2: "20",
    desc2:
      "Play with different animation timing curves based on prototyping tools",
    numb3: "3",
    time3: "8:07",
    intro3: "Peek Scroll",
    width3: "40",
    desc3:
      "Resize and transform elements at the top and bottom of your scroll.",
  },
];
